/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Dec2HexTest2;



import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void InputValidation() {

        assertEquals("Hexadecimal representation is: C", Dec2Hex.hexi(new String[] {"12"}));

    }
@Test
    public void InputValidation2() {

        assertEquals("Hexadecimal representation is: A", Dec2Hex.hexi(new String[] {"10"}));

    }
@Test
    public void InputValidation3() {

        assertEquals("Hexadecimal representation is: F", Dec2Hex.hexi(new String[] {"15"}));

    }

@Test
    public void InputValidation4() {

        assertEquals("nothing was input, try again with an input", Dec2Hex.hexi(new String[0]));

    }

@Test
    public void InputValidation5() {

        assertEquals("This is not a valid input. Enter an Integer", Dec2Hex.hexi(new String[] {"Zebra"}));

    }
}
