/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package Dec2HexTest2;


import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest3 {
    @Test
    public void InputValida3on() {

        assertEquals("This is not a valid input. Enter an Integer", Dec2Hex.hexi(new String[] {"zebra"}));

    }
}
